/**
 * Genres offered in the tag editor next to the ones already in the
 * library. The ID3v1 list with its Winamp extensions is what tag editors
 * have always proposed, and what people expect to find there; it is kept
 * in its usual spelling, since these are tag values, not UI copy — they
 * are never translated.
 *
 * Left out: the entries that are not genres (`Other`, `Sound Clip`,
 * `Trailer`, `Pranks`, `Primus` — a band), and the two that are an insult
 * or plainly out of place in a music player's suggestions. Added: a few
 * genres the 1990s list could not know and a library now holds.
 */
export const GENRE_PRESETS: readonly string[] = [
  "A Cappella",
  "Abstract",
  "Acid",
  "Acid Jazz",
  "Acid Punk",
  "Acoustic",
  "Afrobeats",
  "Alternative",
  "Alternative Rock",
  "Ambient",
  "Anime",
  "Art Rock",
  "Audio Theatre",
  "Audiobook",
  "Avantgarde",
  "Ballad",
  "Baroque",
  "Bass",
  "Beat",
  "Bebop",
  "Bhangra",
  "Big Band",
  "Big Beat",
  "Black Metal",
  "Bluegrass",
  "Blues",
  "Booty Bass",
  "Breakbeat",
  "Britpop",
  "Cabaret",
  "Celtic",
  "Chamber Music",
  "Chanson",
  "Chillout",
  "Chorus",
  "Christian Rap",
  "Christian Rock",
  "City Pop",
  "Classic Rock",
  "Classical",
  "Club",
  "Club-House",
  "Comedy",
  "Contemporary Christian",
  "Country",
  "Crossover",
  "Cult",
  "Dance",
  "Dance Hall",
  "Darkwave",
  "Death Metal",
  "Disco",
  "Downtempo",
  "Dream",
  "Drill",
  "Drum & Bass",
  "Drum Solo",
  "Dub",
  "Dubstep",
  "Duet",
  "Easy Listening",
  "EBM",
  "Eclectic",
  "Electro",
  "Electroclash",
  "Electronic",
  "Emo",
  "Ethnic",
  "Euro-House",
  "Euro-Techno",
  "Eurodance",
  "Experimental",
  "Fast Fusion",
  "Folk",
  "Folk-Rock",
  "Folklore",
  "Freestyle",
  "Funk",
  "Fusion",
  "G-Funk",
  "Game",
  "Gangsta",
  "Garage",
  "Garage Rock",
  "Global",
  "Goa",
  "Gospel",
  "Gothic",
  "Gothic Rock",
  "Grunge",
  "Hard Rock",
  "Hardcore",
  "Heavy Metal",
  "Hip-Hop",
  "House",
  "Humour",
  "IDM",
  "Illbient",
  "Indie",
  "Indie Rock",
  "Industrial",
  "Industro-Goth",
  "Instrumental",
  "Instrumental Pop",
  "Instrumental Rock",
  "J-Pop",
  "J-Rock",
  "Jam Band",
  "Jazz",
  "Jazz+Funk",
  "Jungle",
  "K-Pop",
  "Krautrock",
  "Latin",
  "Leftfield",
  "Lo-Fi",
  "Lounge",
  "Math Rock",
  "Meditative",
  "Merengue",
  "Metal",
  "Metalcore",
  "Musical",
  "National Folk",
  "Native American",
  "Neoclassical",
  "Neue Deutsche Welle",
  "New Age",
  "New Romantic",
  "New Wave",
  "Noise",
  "Nu-Breakz",
  "Oldies",
  "Opera",
  "Podcast",
  "Polka",
  "Polsk Punk",
  "Pop",
  "Pop-Folk",
  "Pop/Funk",
  "Post-Punk",
  "Post-Rock",
  "Power Ballad",
  "Progressive Rock",
  "Psybient",
  "Psychedelic",
  "Psychedelic Rock",
  "Psytrance",
  "Punk",
  "Punk Rock",
  "R&B",
  "Rap",
  "Rave",
  "Reggae",
  "Reggaeton",
  "Retro",
  "Revival",
  "Rhythmic Soul",
  "Rock",
  "Rock & Roll",
  "Salsa",
  "Samba",
  "Satire",
  "Shoegaze",
  "Showtunes",
  "Ska",
  "Slow Jam",
  "Slow Rock",
  "Sonata",
  "Soul",
  "Soundtrack",
  "Southern Rock",
  "Space",
  "Space Rock",
  "Speech",
  "Swing",
  "Symphonic Rock",
  "Symphony",
  "Synthpop",
  "Synthwave",
  "Tango",
  "Techno",
  "Techno-Industrial",
  "Thrash Metal",
  "Top 40",
  "Trance",
  "Trap",
  "Tribal",
  "Trip-Hop",
  "Trop Rock",
  "Vocal",
  "World Music",
];
