use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    sync_updater_capability();
    tauri_build::build();
    generate_changelog();
}

/// Generate or remove `capabilities/updater.json` based on the `updater`
/// Cargo feature.
///
/// Tauri 2 auto-discovers all `capabilities/*.json` files at build time and
/// fails compilation if any referenced permission can't be resolved against
/// the compiled-in plugins. Since `tauri-plugin-updater` is `optional` and
/// only pulled in by the `updater` feature, `updater:default` would dangle
/// in `default.json` when the feature is off (Flatpak, future MAS / MS
/// Store builds). Splitting the permission into its own file lets us
/// write or delete it from build.rs so tauri-build sees exactly what
/// matches the dep graph. The file is gitignored.
fn sync_updater_capability() {
    let path = PathBuf::from("capabilities/updater.json");
    // Cargo exposes feature flags as `CARGO_FEATURE_<NAME>` env vars.
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATER");
    if env::var_os("CARGO_FEATURE_UPDATER").is_some() {
        let contents = concat!(
            "{\n",
            "  \"$schema\": \"../gen/schemas/desktop-schema.json\",\n",
            "  \"identifier\": \"updater\",\n",
            "  \"description\": \"Auto-updater permission, gated on the `updater` Cargo feature. Generated by build.rs.\",\n",
            "  \"windows\": [\"main\", \"mini\"],\n",
            "  \"permissions\": [\"updater:default\"]\n",
            "}\n",
        );
        // Only write if the current on-disk content differs, otherwise
        // every build invalidates the rerun-if-changed=capabilities watch
        // and forces tauri-build to redo codegen.
        let needs_write = match fs::read_to_string(&path) {
            Ok(current) => current != contents,
            Err(_) => true,
        };
        if needs_write {
            // Fail fast: a silent miss here resurfaces later as a
            // tauri-build "unknown permission updater:default" error
            // that's much harder to map back to its real cause.
            fs::write(&path, contents).unwrap_or_else(|err| {
                panic!(
                    "updater capability: failed to write {}: {err}",
                    path.display()
                )
            });
        }
    } else if path.exists() {
        // Same reasoning: a stale updater.json under capabilities/
        // with the feature off blows up tauri-build's validation with
        // a confusing error far from this site.
        fs::remove_file(&path).unwrap_or_else(|err| {
            panic!(
                "updater capability: failed to remove {}: {err}",
                path.display()
            )
        });
    }
}

/// Build-time changelog generator.
///
/// Runs `git log` once at compile time, parses the conventional-commit
/// header (`type(scope): subject`) and writes a JSON array next to the
/// build artefacts. The Tauri backend embeds the result via
/// `include_str!` so the shipped binary carries its own changelog —
/// users without git installed still see it.
///
/// Failure is non-fatal: if git is missing or the working dir isn't a
/// repository, an empty JSON array is written and the About view shows
/// nothing under "Changelog".
fn generate_changelog() {
    let out_dir: PathBuf = env::var_os("OUT_DIR").expect("OUT_DIR not set").into();
    let dest = out_dir.join("changelog.json");

    // Re-run when HEAD moves (new commit, branch switch). We don't
    // watch every ref because in dev that would mean re-emitting the
    // file on every fetch.
    //
    // Paths are relative to CARGO_MANIFEST_DIR of this crate
    // (`src-tauri/crates/app/`); the repo root is three levels up.
    println!("cargo:rerun-if-changed=../../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../../.git/refs/heads");

    let entries = read_git_log().unwrap_or_default();
    let json = serde_json::to_string(&entries).unwrap_or_else(|_| "[]".into());
    if let Err(err) = fs::write(&dest, json) {
        println!(
            "cargo:warning=changelog: failed to write {}: {err}",
            dest.display()
        );
        let _ = fs::write(&dest, "[]");
    }
}

fn read_git_log() -> Option<Vec<ChangelogEntry>> {
    // %h hash, %s subject, %cI committer date ISO-8601 strict.
    // Fields separated by U+001F (unit), records by U+001E (record).
    let output = Command::new("git")
        .args([
            "log",
            "--max-count=300",
            "--no-merges",
            "--pretty=format:%h\x1f%s\x1f%cI\x1e",
        ])
        // CARGO_MANIFEST_DIR is `src-tauri/crates/app/`; the repo root
        // sits three levels up.
        .current_dir("../../..")
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let raw = String::from_utf8_lossy(&output.stdout);
    let entries = raw
        .split('\x1e')
        .filter_map(|record| {
            let trimmed = record.trim();
            if trimmed.is_empty() {
                return None;
            }
            let mut parts = trimmed.splitn(3, '\x1f');
            let hash = parts.next()?.trim().to_string();
            let subject = parts.next()?.trim().to_string();
            let date = parts.next()?.trim().to_string();
            parse_entry(hash, subject, date)
        })
        .collect();
    Some(entries)
}

#[derive(serde::Serialize)]
struct ChangelogEntry {
    hash: String,
    /// Conventional-commit type (`feat`, `fix`, `chore`, …).
    #[serde(rename = "type")]
    kind: String,
    scope: Option<String>,
    subject: String,
    breaking: bool,
    /// ISO-8601 committer date.
    date: String,
}

/// Parse a conventional-commit subject line. Returns `None` for commits
/// that don't match the format so they're omitted from the rendered
/// changelog (keeps marketing-style noise out).
fn parse_entry(hash: String, subject: String, date: String) -> Option<ChangelogEntry> {
    let (header, rest) = subject.split_once(": ")?;
    if rest.is_empty() {
        return None;
    }
    let (kind, scope, breaking) = parse_header(header)?;
    Some(ChangelogEntry {
        hash,
        kind: kind.to_string(),
        scope: scope.map(str::to_string),
        subject: rest.to_string(),
        breaking,
        date,
    })
}

/// Header is `type` or `type(scope)`, optionally followed by `!` to
/// flag a breaking change. Returns the type, the optional scope and
/// the breaking flag.
fn parse_header(header: &str) -> Option<(&str, Option<&str>, bool)> {
    let (head, breaking) = match header.strip_suffix('!') {
        Some(s) => (s, true),
        None => (header, false),
    };
    if let Some((kind, rest)) = head.split_once('(') {
        let scope = rest.strip_suffix(')')?;
        Some((kind, Some(scope), breaking))
    } else {
        Some((head, None, breaking))
    }
}
