// Stable category IDs preserve existing links and remembered selections.
export const SETTINGS_CATEGORIES = [
  {
    id: "general",
    labelKey: "settings.organization.categories.general",
    descriptionKey: "settings.organization.descriptions.general",
    groups: [
      {
        id: "language",
        labelKey: "settings.organization.groups.language",
        searchKeys: ["settings.language.title", "settings.language.subtitle"],
      },
      {
        id: "startup",
        labelKey: "settings.organization.groups.startup",
        searchKeys: [
          "settings.autoStart.title",
          "settings.autoStart.subtitle",
          "settings.minimizeToTray.title",
          "settings.minimizeToTray.subtitle",
          "settings.integrations.notifications.title",
          "settings.integrations.notifications.subtitle",
        ],
      },
    ],
  },
  {
    id: "library",
    labelKey: "settings.organization.categories.library",
    descriptionKey: "settings.organization.descriptions.library",
    groups: [
      {
        id: "scanning",
        labelKey: "settings.organization.groups.scanning",
        searchKeys: [
          "settings.scanOnStart.title",
          "settings.scanOnStart.subtitle",
          "settings.rescan.title",
          "settings.rescan.subtitle",
          "settings.rescan.action",
          "settings.duplicates.title",
          "settings.duplicates.subtitle",
          "settings.duplicates.action",
        ],
      },
      {
        id: "analysis",
        labelKey: "settings.organization.groups.analysis",
        searchKeys: [
          "settings.analyze.title",
          "settings.analyze.subtitle",
          "settings.analyze.action",
          "settings.analyze.autoTitle",
          "settings.analyze.autoSubtitle",
        ],
      },
      {
        id: "radio",
        labelKey: "settings.organization.groups.radio",
        searchKeys: [
          "settings.radioCatalogue.neverSynced",
          "settings.radioCatalogue.title",
          "settings.radioCatalogue.subtitle",
          "settings.radioCatalogue.clear",
          "settings.radioCatalogue.offlineHint",
          "settings.radioCatalogue.downloading",
          "settings.radioCatalogue.refresh",
          "settings.radioCatalogue.download",
          "settings.radioCatalogue.localFirst",
          "settings.radioCatalogue.localFirstHint",
        ],
      },
    ],
  },
  {
    id: "playback",
    labelKey: "settings.organization.categories.playback",
    descriptionKey: "settings.organization.descriptions.playback",
    groups: [
      {
        id: "transitions",
        labelKey: "settings.organization.groups.transitions",
        searchKeys: [
          "settings.gapless.title",
          "settings.gapless.subtitle",
          "settings.crossfade.title",
          "settings.crossfade.subtitle",
          "settings.smartCrossfade.title",
          "settings.smartCrossfade.subtitle",
          "settings.dynamicCrossfade.title",
          "settings.dynamicCrossfade.subtitle",
        ],
      },
      {
        id: "listening",
        labelKey: "settings.organization.groups.listening",
        searchKeys: [
          "settings.singleClickPlay.title",
          "settings.singleClickPlay.subtitle",
          "settings.generatorAlbumMode.title",
          "settings.generatorAlbumMode.subtitle",
          "settings.pauseOnDeviceLoss.title",
          "settings.pauseOnDeviceLoss.subtitle",
        ],
      },
      {
        id: "volume",
        labelKey: "settings.organization.groups.volume",
        searchKeys: [
          "settings.normalize.title",
          "settings.normalize.subtitle",
          "settings.replayGain.title",
          "settings.replayGain.subtitle",
          "settings.replayGain.preamp.title",
          "settings.replayGain.preamp.subtitle",
          "settings.replayGain.fallback.title",
          "settings.replayGain.fallback.subtitle",
          "settings.replayGain.mode.title",
          "settings.replayGain.preventClipping.title",
          "settings.replayGain.preventClipping.subtitle",
        ],
      },
      {
        id: "equalizer",
        labelKey: "settings.organization.groups.equalizer",
        searchKeys: [
          "settings.equalizer.title",
          "settings.equalizer.subtitle",
          "settings.equalizer.presets",
          "settings.equalizer.preset.custom",
          "settings.equalizer.reset",
        ],
      },
      {
        id: "output",
        labelKey: "settings.organization.groups.output",
        searchKeys: [
          "settings.matchSourceRate.title",
          "settings.matchSourceRate.subtitle",
          "settings.mono.title",
          "settings.mono.subtitle",
          "settings.dsdPrecision.title",
          "settings.dsdPrecision.subtitle",
          "settings.dsdPrecision.standard",
          "settings.dsdPrecision.high",
          "settings.dsdPrecision.max",
          "settings.dsdDop.title",
          "settings.dsdDop.subtitle",
          "settings.exclusive.fallback",
          "settings.exclusive.title",
          "settings.exclusive.subtitle",
        ],
      },
    ],
  },
  {
    id: "appearance",
    labelKey: "settings.organization.categories.appearance",
    descriptionKey: "settings.organization.descriptions.appearance",
    groups: [
      {
        id: "theme",
        labelKey: "settings.organization.groups.theme",
        searchKeys: [
          "settings.appearance.theme.title",
          "settings.appearance.theme.subtitle",
          "settings.uiZoom.title",
          "settings.uiZoom.subtitle",
          "settings.uiZoom.decreaseAria",
          "settings.uiZoom.resetAria",
          "settings.uiZoom.increaseAria",
          "settings.appearance.skin.title",
          "settings.appearance.skin.subtitle",
          "settings.contrast.title",
          "settings.contrast.subtitle",
        ],
      },
      {
        id: "player",
        labelKey: "settings.organization.groups.player",
        searchKeys: [
          "settings.playerBarLayout.title",
          "settings.playerBarLayout.subtitle",
          "settings.playerBarLayout.preview",
          "settings.playerBarLayout.previewEmpty",
          "settings.playerBarLayout.coverAction.title",
          "settings.hiResBadge.title",
          "settings.hiResBadge.subtitle",
          "settings.scrollTitles.title",
          "settings.scrollTitles.subtitle",
          "settings.windowBounds.title",
          "settings.windowBounds.subtitle",
          "settings.windowBounds.done",
          "settings.windowBounds.reset",
        ],
      },
      {
        id: "immersive",
        labelKey: "settings.organization.groups.immersive",
        searchKeys: [
          "settings.visualizer.title",
          "settings.visualizer.subtitle",
          "settings.immersiveView.mergedLyrics.title",
          "settings.immersiveView.mergedLyrics.subtitle",
          "settings.immersiveView.nativeFullscreen.title",
          "settings.immersiveView.nativeFullscreen.subtitle",
          "settings.immersiveView.title",
          "settings.coverSlideshow.title",
          "settings.coverSlideshow.subtitle",
        ],
      },
      {
        id: "desktopLyrics",
        labelKey: "settings.organization.groups.desktopLyrics",
        searchKeys: [
          "desktopLyrics.title",
          "desktopLyrics.lock",
          "desktopLyrics.lockHint",
          "settings.desktopLyrics.subtitle",
          "settings.desktopLyrics.fontSize",
          "settings.desktopLyrics.textColor",
          "settings.desktopLyrics.highlightColor",
          "settings.desktopLyrics.outline",
          "settings.desktopLyrics.background",
          "settings.desktopLyrics.showTranslation",
        ],
      },
      {
        id: "pages",
        labelKey: "settings.organization.groups.pages",
        searchKeys: [
          "settings.artistHero.title",
          "settings.artistHero.subtitle",
          "settings.statsKpis.title",
          "settings.statsKpis.subtitle",
          "settings.statsKpis.legend",
          "settings.wrappedBanner.title",
          "settings.wrappedBanner.subtitle",
          "settings.wrappedBanner.seasonActive",
          "settings.wrappedBanner.seasonIdle",
          "settings.wrappedBanner.legend",
        ],
      },
    ],
  },
  {
    id: "media",
    labelKey: "settings.organization.categories.media",
    descriptionKey: "settings.organization.descriptions.media",
    groups: [
      {
        id: "artwork",
        labelKey: "settings.organization.groups.artwork",
        searchKeys: [
          "settings.localArtistImages.title",
          "settings.localArtistImages.subtitle",
          "settings.localArtistImages.action",
          "settings.artistImages.title",
          "settings.artistImages.subtitle",
          "settings.artistImages.action",
          "library.fetchMissingCovers",
        ],
      },
      {
        id: "biographies",
        labelKey: "settings.organization.groups.biographies",
        searchKeys: [
          "settings.artistBio.title",
          "settings.artistBio.subtitle",
          "settings.artistBio.languageLabel",
        ],
      },
      {
        id: "lyrics",
        labelKey: "settings.organization.groups.lyrics",
        searchKeys: [
          "settings.lyricsPrefetch.title",
          "settings.lyricsPrefetch.subtitle",
          "settings.lyricsPrefetch.action",
          "settings.lyricsTranslation.title",
          "settings.lyricsTranslation.subtitle",
          "settings.lyricsTranslation.off",
          "settings.lyricsPreferLrclib.title",
          "settings.lyricsPreferLrclib.subtitle",
          "settings.lyricsDestination.title",
          "settings.lyricsDestination.subtitle",
          "settings.fullscreenLyricsCentering.title",
          "settings.fullscreenLyricsCentering.subtitle",
        ],
      },
    ],
  },
  {
    id: "integrations",
    labelKey: "settings.organization.categories.integrations",
    descriptionKey: "settings.organization.descriptions.integrations",
    groups: [
      {
        id: "connectivity",
        labelKey: "settings.organization.groups.connectivity",
        searchKeys: [
          "settings.offlineMode.title",
          "settings.offlineMode.subtitle",
        ],
      },
      {
        id: "services",
        labelKey: "settings.organization.groups.services",
        searchKeys: [
          "settings.integrations.lastfm.title",
          "settings.integrations.lastfm.subtitle",
          "settings.integrations.lastfm.placeholder",
          "settings.integrations.lastfm.hide",
          "settings.integrations.lastfm.show",
          "settings.integrations.lastfm.secretPlaceholder",
          "settings.integrations.lastfm.save",
          "settings.integrations.lastfm.connectedAs",
          "settings.integrations.lastfm.loginPrompt",
          "settings.integrations.lastfm.usernamePlaceholder",
          "settings.integrations.lastfm.passwordPlaceholder",
          "settings.integrations.lastfm.connect",
          "settings.integrations.discord.title",
          "settings.integrations.discord.subtitle",
        ],
      },
      {
        id: "remote",
        labelKey: "settings.organization.groups.remote",
        searchKeys: [
          "remote.server.title",
          "remote.server.subtitle",
          "remote.server.urlLabel",
          "remote.server.identify",
          "remote.server.unknownType",
          "remote.server.probeNative",
          "remote.server.probeSubsonic",
          "remote.server.signInBrowser",
          "remote.server.signedInFallback",
          "remote.server.syncNow",
          "remote.server.signOut",
          "remote.server.forgetTitle",
          "remote.server.forget",
          "remote.server.neverSynced",
          "settings.remoteTranscode.title",
          "settings.remoteTranscode.subtitle",
          "settings.remoteTranscode.bitrateLabel",
          "settings.remoteTranscode.activeNotice",
          "settings.remoteTranscode.unsupported",
          "remote.catalogue.title",
          "remote.catalogue.subtitle",
          "remote.catalogue.mirror",
          "remote.catalogue.statAlbums",
          "remote.catalogue.statTracks",
          "remote.catalogue.statArtists",
          "remote.catalogue.statLibraries",
          "remote.catalogue.reportUnchanged",
          "remote.catalogue.clearCovers",
          "remote.catalogue.clearStreams",
          "remote.catalogue.clearDownloads",
          "remote.catalogue.neverMirrored",
          "remote.catalogue.clearConfirm",
          "remote.catalogue.clearAbort",
          "remote.catalogue.clear",
          "remote.upload.title",
          "remote.upload.subtitle",
          "remote.upload.survey",
          "remote.upload.statMissing",
          "remote.upload.statLinked",
          "remote.upload.statUnsupported",
          "remote.upload.statUnreadable",
          "remote.needsMirror",
          "remote.upload.destination",
          "remote.upload.stopped",
          "remote.reconciliation.title",
          "remote.reconciliation.subtitle",
          "remote.reconciliation.findMatches",
          "remote.reconciliation.confirmedLinks",
          "remote.reconciliation.yes",
          "remote.reconciliation.no",
          "remote.reconciliation.copyFavoriteLocalToServer",
          "remote.reconciliation.copyFavoriteServerToLocal",
          "remote.reconciliation.copyRatingLocalToServer",
          "remote.reconciliation.copyRatingServerToLocal",
          "remote.reconciliation.statusStale",
          "remote.reconciliation.statusConfirmed",
          "remote.reconciliation.localFirst",
          "remote.reconciliation.serverFirst",
          "remote.reconciliation.conversionTitle",
          "remote.reconciliation.conversionSubtitle",
          "remote.reconciliation.conversionDirection",
          "remote.reconciliation.conversionLocalToServer",
          "remote.reconciliation.conversionServerToLocal",
          "remote.reconciliation.conversionSource",
          "remote.reconciliation.conversionNoPlaylists",
          "remote.reconciliation.conversionPreview",
          "remote.reconciliation.conversionConfirm",
          "remote.reconciliation.candidateHeading",
          "remote.reconciliation.candidateLocalTrack",
          "remote.reconciliation.candidateServerTrack",
          "remote.reconciliation.candidateConfirmPair",
          "remote.reconciliation.candidateRejectPair",
        ],
      },
      {
        id: "network",
        labelKey: "settings.organization.groups.network",
        searchKeys: [
          "settings.integrations.dlna.title",
          "settings.integrations.dlna.subtitle",
          "settings.integrations.dlna.serverName",
          "settings.integrations.dlna.port",
          "settings.integrations.dlna.portHint",
          "settings.integrations.dlna.copyUrl",
          "settings.integrations.mpd.title",
          "settings.integrations.mpd.subtitle",
          "settings.integrations.mpd.lanWarningAuth",
          "settings.integrations.mpd.lanWarning",
          "settings.integrations.mpd.port",
          "settings.integrations.mpd.portHint",
          "settings.integrations.mpd.password",
          "settings.integrations.mpd.passwordPlaceholder",
          "settings.integrations.mpd.passwordHint",
          "settings.integrations.mpd.copyAddress",
        ],
      },
    ],
  },
  {
    id: "plugins",
    labelKey: "settings.organization.categories.plugins",
    descriptionKey: "settings.organization.descriptions.plugins",
    groups: [
      {
        id: "extensions",
        labelKey: "settings.organization.groups.extensions",
        searchKeys: [
          "settings.pluginStore.title",
          "settings.pluginStore.subtitle",
          "settings.pluginStore.refresh",
          "settings.pluginStore.retry",
          "settings.pluginStore.loading",
          "settings.pluginStore.emptyTitle",
          "settings.pluginStore.emptyHint",
          "settings.pluginStore.official",
          "settings.pluginStore.incompatibleHint",
          "settings.pluginStore.incompatible",
          "settings.pluginStore.installed",
          "settings.pluginStore.installing",
          "settings.pluginStore.update",
          "settings.pluginStore.install",
          "settings.plugins.worlds.source",
          "settings.plugins.worlds.metadata",
          "settings.plugins.worlds.ui",
          "settings.plugins.permissions.none",
          "settings.pluginStore.canReach",
          "settings.plugins.permissions.storageState",
          "settings.plugins.permissions.storageRead",
          "settings.plugins.permissions.libraryReadArtists",
          "settings.plugins.title",
          "settings.plugins.subtitle",
          "settings.plugins.loading",
          "settings.plugins.emptyTitle",
          "settings.plugins.emptyHint",
          "settings.plugins.enabled",
          "settings.plugins.disabled",
          "settings.plugins.bundledHint",
          "settings.plugins.bundled",
          "settings.plugins.confirmYes",
          "settings.plugins.confirmNo",
          "settings.plugins.uninstall",
        ],
      },
    ],
  },
  {
    id: "shortcuts",
    labelKey: "settings.organization.categories.shortcuts",
    descriptionKey: "settings.organization.descriptions.shortcuts",
    groups: [
      {
        id: "keyboard",
        labelKey: "settings.organization.groups.keyboard",
        searchKeys: [
          "settings.shortcuts.subtitle",
          "settings.shortcuts.reset",
          "settings.shortcuts.captureHint",
          "settings.shortcuts.unbound",
          "settings.shortcuts.unbind",
        ],
      },
    ],
  },
  {
    id: "data",
    labelKey: "settings.organization.categories.data",
    descriptionKey: "settings.organization.descriptions.data",
    groups: [
      {
        id: "backups",
        labelKey: "settings.organization.groups.backups",
        searchKeys: [
          "settings.profileIo.title",
          "settings.profileIo.subtitle",
          "settings.profileIo.export.action",
          "settings.profileIo.import.action",
          "settings.backup.pickFolderTitle",
          "settings.backup.neverRun",
          "settings.backup.title",
          "settings.backup.subtitle",
          "settings.backup.intervalLabel",
          "settings.backup.retentionLabel",
          "settings.backup.includeMetadataArtworkLabel",
          "settings.backup.includeMetadataArtworkHint",
          "settings.backup.changeFolder",
          "settings.backup.runNow",
        ],
      },
      {
        id: "storage",
        labelKey: "settings.organization.groups.storage",
        searchKeys: [
          "settings.dataFolder.title",
          "settings.dataFolder.subtitle",
          "settings.openDataFolder",
          "settings.dataFolder.action",
          "settings.cacheLocation.pickTitle",
          "settings.cacheLocation.title",
          "settings.cacheLocation.subtitle",
          "settings.cacheLocation.choose",
          "settings.cacheLocation.reset",
          "settings.cacheLocation.copying",
          "settings.cacheLocation.restartNeeded",
          "settings.cacheLocation.restartNow",
        ],
      },
      {
        id: "cleanup",
        labelKey: "settings.organization.groups.cleanup",
        searchKeys: [
          "settings.regenerateThumbnails",
          "settings.regenerateThumbnailsSubtitle",
          "settings.regenerateThumbnailsAction",
          "settings.pruneAlbumCovers",
          "settings.pruneAlbumCoversSubtitle",
          "settings.pruneAlbumCoversAction",
        ],
      },
    ],
  },
  {
    id: "diagnostics",
    labelKey: "settings.organization.categories.diagnostics",
    descriptionKey: "settings.organization.descriptions.diagnostics",
    groups: [
      {
        id: "updates",
        labelKey: "settings.organization.groups.updates",
        searchKeys: [
          "settings.updateChannel.title",
          "settings.updateChannel.subtitle",
        ],
      },
      {
        id: "diagnostics",
        labelKey: "settings.organization.groups.diagnostics",
        searchKeys: [
          "settings.diagnostics.title",
          "settings.diagnostics.subtitle",
          "settings.diagnostics.openFolder",
          "settings.diagnostics.copyLogs",
          "rendering.card.title",
          "rendering.card.restartToApply",
          "rendering.card.retryGpu",
        ],
      },
      {
        id: "reset",
        labelKey: "settings.organization.groups.reset",
        searchKeys: [
          "settings.reset.title",
          "settings.reset.subtitle",
          "settings.reset.action",
        ],
      },
    ],
  },
] as const;

export type SettingsCategory = (typeof SETTINGS_CATEGORIES)[number]["id"];
